language: python
python:
  - "2.7"
  - "3.3"
services: mongodb
script: "nosetests test"

env:
  - FUTURES=yes
  - FUTURES=no
matrix:
  exclude:
    - python: "3.3"
      env: FUTURES=yes
before_script:
  - if [[ "$FUTURES" == "yes" ]]; then pip install futures; fi

branches:
  only:
    - master
    - stable