language: python
python:
  - "2.7"
services: mongodb
script: "nosetests test"

env:
  - FUTURES=yes
  - FUTURES=no

before_script:
  - if [[ "$FUTURES" == "yes" ]]; then pip install futures; fi

branches:
  only:
    - master
    - stable